sudo: false
language: node_js
node_js:
  - lts/*
branches:
  only:
    - main
script:
  - yarn run build
deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  target_branch: travis_branch
  keep-history: false
  on:
    branch: main
  local-dir: out
